// Generated by CoffeeScript 2.0.1
(function() {
  var Hapi, server;

  Hapi = require('hapi');

  // create a server with a host and port
  server = new Hapi.Server();

  server.connection({
    host: 'localhost',
    port: 8000
  });

  // add the route
  server.route({
    method: 'GET',
    path: '/hello',
    handler: function(request, reply) {
      return reply('hello world');
    }
  });

  // start the server
  server.start((err) => {
    if (err) {
      throw err;
    }
    return console.log('Server running at:', server.info.uri);
  });

}).call(this);
